### ISSUE TITLE
Manage projects

### ISSUE THREAD

**Issue by RubenvanGemeren** [RubenvanGemeren/digital_portfolio#9]
## Description
Within the app, projects should be added, updated and deleted. In order to write the article a feature from naive ui named 'dynamic input' will be used. Project management will use standard laravel to validate, store, update, and delete records. A authenticated view needs to be made where projects can be created.

### References
- [Naive UI Dynamic Input](https://www.naiveui.com/en-US/os-theme/components/dynamic-input)

### Tasks
- [ ] Create 'create project' view
- [ ] Store object after validation
- [ ] Create 'update/delete project' view
- [ ] Modify object after validation
